package com.dbanalyzer.dbpkproject.database.dynamo.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.dbanalyzer.dbpkproject.csv.dto.MovieGenreDto;
import lombok.Data;

import java.util.Collection;

@Data
@DynamoDBTable(tableName = "Movie")
@DynamoDBDocument
public class Movie {

    private String id;
    private String name;
    private Integer year;
    private Float rank;
    private MovieGenreDto movieGenre;
    private Collection<Role> roles;
    private Collection<Director> directors;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

}